#!/usr/bin/env python3
"""Regenerate tests/expected_resources.tsv from the intended requests, computed here independently of Nextflow:
per-process cpus / memory / time (conf/hazel.config), short's 1 h cap, normal's routing (<= 105 min -> compute_partners)."""
import math

GIB = 2 ** 30
FLOOR_MIN = 15
# process: (cpus, memory, fixed time in min or (a, b) h + h/GiB)
REQ = {
    'DEMUX': (6, '2 GB', 60), 'MERGE_LANES': (4, '1 GB', 30), 'DEMUX_QC': (1, '1 GB', 10),
    'TRIMMOMATIC': (6, '2 GB', (0.1, 0.105)), 'FASTQC': (2, '3 GB', (0.1, 0.032)),
    'ALIGN_MARKDUP': (8, '48 GB', (0.25, 0.323)), 'SAMTOOLS_STATS': (2, '1 GB', (0.1, 0.06)),
    'PICARD_COLLECTWGSMETRICS': (1, '5 GB', (0.21, 0.174)), 'PROVENANCE': (1, '1 GB', 10),
    'REGISTRY': (1, '1 GB', 10), 'MULTIQC': (1, '2 GB', 30), 'MARKDUP_IMPORT': (4, '12 GB', 30),
}
ORDER = ['DEMUX', 'MERGE_LANES', 'DEMUX_QC', 'TRIMMOMATIC', 'FASTQC', 'ALIGN_MARKDUP', 'SAMTOOLS_STATS',
         'PICARD_COLLECTWGSMETRICS', 'PROVENANCE', 'REGISTRY', 'MULTIQC', 'MARKDUP_IMPORT']
PROBED = ['TRIMMOMATIC', 'FASTQC', 'ALIGN_MARKDUP', 'SAMTOOLS_STATS', 'PICARD_COLLECTWGSMETRICS']
# probe input bytes per pair (scripts/check_resources.sh): raw pair 136, trimmed pair 107, CRAM 41
PROBE_BPP = {'TRIMMOMATIC': 136, 'FASTQC': 107, 'ALIGN_MARKDUP': 107, 'SAMTOOLS_STATS': 41, 'PICARD_COLLECTWGSMETRICS': 41}


def minutes(proc, nbytes=0):
    t = REQ[proc][2]
    if isinstance(t, int):
        return t
    a, b = t
    h = max(FLOOR_MIN / 60, a + b * nbytes / GIB)
    return math.ceil(round(60 * h, 9))


def fmt(m):
    h, mm = divmod(m, 60)
    return f'{h}h {mm}m' if h and mm else (f'{h}h' if h else f'{mm}m')


def row(prof, proc, m):
    cpus, mem = REQ[proc][0], REQ[proc][1]
    if prof.startswith('short'):
        m, q = min(m, 60), 'compute_partners'
    else:
        q = 'compute_partners' if m <= 105 else 'compute'
    return f'{prof}\t{proc}\t{cpus}\t{mem}\t{fmt(m)}\t{q}'


out = [
    '# Intended resources per process on hazel, checked by scripts/check_resources.sh against -stub runs\' traces (first attempt).',
    '# profile = the second profile next to `hazel` (-profile hazel,<profile>). Values are written as the trace prints them.',
    '# Requests: conf/hazel.config (both profiles); per-sample times = max(15 min, a + b x GiB of the task\'s input), rounded up',
    '# to the minute; the fixture / stub inputs are tiny, so they get the 15 min floor (ALIGN_MARKDUP 16m: its 0.25 h\n# intercept plus a few stub bytes, rounded up). short: every time capped at 1 h, all on',
    '# compute_partners (conf/short.config). normal: 24 h limit, a task asking <= 1 h 45 on compute_partners / short QOS, else on',
    '# compute / normal QOS (conf/normal.config). <profile>_100M / <profile>_310M rows: the size probe (sparse inputs of a',
    '# 100 M / 310 M pair sample: 136 B per raw pair, 107 B per trimmed pair, 41 B of CRAM per pair; scripts/check_resources.sh).',
    '# DEMUX cpus 6 = a bc1 library (the fixture LIBX; other sources get 4). ALIGN_MARKDUP memory = params.align_memory_gb.',
    '# Generated by agent/20260928_235800_write_expected_resources.py (kept out of git; regenerate or edit by hand).',
    'profile\tprocess\tcpus\tmemory\ttime\tqueue',
]
for prof in ('normal', 'short'):
    out += [row(prof, p, minutes(p, 1)) for p in ORDER]  # stub files are a few bytes: ALIGN's 0.25 h intercept + bytes -> 16m
for prof in ('normal', 'short'):
    for tag, pairs in (('100M', 100e6), ('310M', 310e6)):
        out += [row(f'{prof}_{tag}', p, minutes(p, int(pairs * PROBE_BPP[p] / 2) * 2 if PROBE_BPP[p] != 41 else int(pairs * 41)))
                for p in PROBED]
out += ['normal_batch1\tDEMUX\t4\t2 GB\t2h\tcompute', 'short_batch1\tDEMUX\t4\t2 GB\t1h\tcompute_partners']
open('tests/expected_resources.tsv', 'w').write('\n'.join(out) + '\n')
print('\n'.join(out))
