# Env round task 4: ONE list of deliberate deviations from the nf-core specifications, written verbatim into .nf-core.yml
# (as comments), docs/usage.md, docs/PLAN_pipeline.md §2 and the nfcore-compliance skill's "This repository" section.
# Rerunnable: each target has a marked region that is replaced.
import re
import textwrap
from pathlib import Path

R = Path("/Users/fvrodriguez/repos/zealgt-simplify")

INTRO = ("Deliberate deviations from the nf-core specifications. The same list, word for word, is in `.nf-core.yml`, "
         "`docs/usage.md`, `docs/PLAN_pipeline.md` §2 and the nfcore-compliance skill; a new deviation goes into all four, "
         "with its reason.")
ITEMS = [
    "**No containers** (spec: Docker / Singularity support). Hazel compute nodes are offline and run no container engine "
    "for this project; every module has a pinned `environment.yml` instead. The template's container configs "
    "(`conf/containers_*.config`) are removed and gitignored (`nf-core modules install/patch` regenerates them), and the "
    "`container_configs` lint test is off.",
    "**No GitHub Actions CI** (spec: CI testing). The pipeline runs on a private offline cluster; `scripts/run_checks.sh` "
    "runs the same checks on the laptop before every push (nf-core lint, schema lint, nextflow lint, nf-test, the env "
    "prefix and resolved-resource checks; docs/CONTRIBUTING.md).",
    "**Build-pinned conda prefixes set per process in the site config** (spec: conda packages pinned by version, envs "
    "created by Nextflow). `conf/env_prefixes.config`, generated by `scripts/build_envs.sh --write-config` and included by "
    "the hazel and local profiles only, sets each process's `conda` to a prebuilt prefix on `/share` (config `conda` "
    "overriding the module's, the standard Nextflow override). A prefix is keyed on the content of `environment.yml` "
    "(+ `build.sh`) only, so identical envs share one prefix; local modules pin version and build (linux-64 is the only "
    "target); the prefixes are built once by an xfer job (compute nodes are offline), never at task time.",
    "**Cache test as an operator script, not an nf-test** (spec: tests are nf-test). `scripts/test_cache.sh` resumes one "
    "Nextflow session across several runs (raised resources, an edited module, stage 2 alone) and compares the task "
    "hashes; nf-test starts a new session for every run and cannot share one.",
    "**Permanent store and FASTQ checkpoint outside `--outdir`** (spec: outputs published to `--outdir`). CRAMs, QC, "
    "provenance, demux QC and the registry are copied into `--store` (never overwritten) and the workflow skips work whose "
    "stored output exists; the trimmed pairs are hardlinked into `--fastq_checkpoint` (the filesystem of `work/`), with "
    "TRIMMOMATIC's small trim reports (one `publishDir` map: a second one whose path uses `meta` breaks "
    "`nextflow config -o json`, so nf-core lint). Only reports go to `--outdir`.",
    "**`versions.yml` files for five local modules** (spec: versions as `eval` topic tuples). ALIGN_MARKDUP and "
    "MARKDUP_IMPORT publish theirs next to the CRAM, one line per tool of the pipe, because PROVENANCE of an already stored "
    "CRAM (skipped, not made again) needs the versions of the tools that made it; DEMUX_QC, PROVENANCE and REGISTRY are "
    "python module templates, and Nextflow allows `eval` outputs only with Bash scripts. DEMUX and the nf-core modules "
    "report `eval` topic tuples; coreutils (DEMUX's `head`, MERGE_LANES's `cat`) is pinned in `environment.yml` but not "
    "reported (the BSD tools of the laptop's local runs have no `--version`).",
    "**Stage-2 samplesheet written by the pipeline** (spec: inputs through `--input`). "
    "`<fastq_checkpoint>/<lib>/samplesheet.csv` is an output of stage 1 and the only input of `--entry read_alignment`, "
    "validated by nf-schema against `assets/schema_checkpoint.json`.",
    "**`--subsample` / `--max_libraries` typed integer-or-string** (spec: typed parameters). Nextflow 26 hands CLI values "
    "over as strings; the schema accepts digit strings and the code converts.",
    "**Per-source read structures as two parameters** (`read_structure_*`, chosen by `barcode_layout`), not one per sample; "
    "both values are recorded in every provenance record.",
    "**CRAM output only, no `--bam`**: the genotype workflow reads CRAM.",
]


def md_block(indent=""):
    lines = [indent + l for l in textwrap.wrap(INTRO, 124 - len(indent))]
    for it in ITEMS:
        w = textwrap.wrap(it, 124 - len(indent) - 2)
        lines.append(indent + "- " + w[0])
        lines += [indent + "  " + l for l in w[1:]]
    return "\n".join(lines) + "\n"


def yml_block():
    plain = [INTRO] + ["- " + it for it in ITEMS]
    out = ["# zealgt BEGIN deliberate deviations (agent/20260929_131500_write_deviations.py writes all four copies)"]
    for p in plain:
        w = textwrap.wrap(p, 120, subsequent_indent="  " if p.startswith("- ") else "")
        out += ["#   " + l for l in w]
    out.append("# zealgt END deliberate deviations")
    return "\n".join(out) + "\n"


def replace_region(path, pattern, new, flags=re.S):
    t = path.read_text()
    t2, n = re.subn(pattern, lambda _m: new, t, flags=flags)
    assert n == 1, (path, n)
    path.write_text(t2)


# .nf-core.yml: the old comment block (or the marked region) between nf_core_version and lint:
replace_region(R / ".nf-core.yml",
               r"(?:# zealgt deliberate deviations from the nf-core pipeline requirements.*?|# zealgt BEGIN deliberate deviations.*?# zealgt END deliberate deviations\n)(?=lint:\n)",
               yml_block())

# docs/usage.md: the whole last section
replace_region(R / "docs/usage.md", r"## Deliberate deviations from the nf-core specifications\n.*\Z",
               "## Deliberate deviations from the nf-core specifications\n\n" + md_block())

# docs/PLAN_pipeline.md: a subsection at the end of §2 (before ## 3.)
plan = R / "docs/PLAN_pipeline.md"
t = plan.read_text()
sec = "### Deliberate deviations from nf-core\n" + md_block() + "\n"
if "### Deliberate deviations from nf-core\n" in t:
    t, n = re.subn(r"### Deliberate deviations from nf-core\n.*?\n(?=## 3\. )", lambda _m: sec, t, flags=re.S)
else:
    t, n = re.subn(r"\n(?=## 3\. Two workflows)", lambda _m: "\n" + sec, t)
assert n == 1, ("plan", n)
plan.write_text(t)

# skill: the "Deliberate deviations" bullet of "This repository"
replace_region(R / ".claude/skills/nfcore-compliance/SKILL.md",
               r"- (?:Deliberate deviations, recorded with reasons in `\.nf-core\.yml`.*?Add new ones there, with a reason\.\n|Deliberate deviations from the nf-core specifications\. The same list.*?\n(?=- \*\*Never (?:edit|change)))",
               "- " + md_block("  ")[2:])
print("written")
